name: Deptry Dependency Check

on: [pull_request]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install GMT
        run: sudo apt-get update && sudo apt-get install -y gmt libgmt-dev ghostscript gdal-bin libgdal-dev

      - run: uv run --all-groups deptry .
