name: Pytest Check

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gmt, libgmt-dev, ghostscript
          version: 1.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run tests
        run: |
          pytest --cov=source_modelling tests
          
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .coverage.*
          include-hidden-files: true
          if-no-files-found: ignore

      
